application: armandict-dev
version: 1
runtime: python
api_version: 1

builtins:
#- remote_api: on
- datastore_admin: on

handlers:
- url: /styles
  static_dir: StaticData/styles
  
- url: /styles/images
  static_dir: StaticData/styles/images

- url: /images
  static_dir: StaticData/images
  
- url: /jscripts
  static_dir: StaticData/jscripts
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /.*
  script: main.py

